drop table agg_test;
create table agg_test(id int, iv int, sv char, dv date, fv float);
insert into agg_test values(1, 1, "FNC", "2011-11-1", 3.0);
insert into agg_test values(2, 2, "TPA", "2012-11-1", 3.0);
insert into agg_test values(3, 3, "SKT", "2013-11-1", 3.0);
insert into agg_test values(4, 4, "SSW", "2014-11-1", 3.1);
select * from agg_test;
select max(iv) from agg_test;
select max(sv) from agg_test;
select max(dv) from agg_test;
select max(fv) from agg_test;
select min(iv) from agg_test;
select min(sv) from agg_test;
select min(dv) from agg_test;
select min(fv) from agg_test;
select count(*) from agg_test;
select count(10) from agg_test;
select avg(iv) from agg_test;
select avg(fv) from agg_test;
select avg(2) from agg_test;
select max(agg_test.iv) from agg_test;
select max(agg_test.sv) from agg_test;
select max(agg_test.dv) from agg_test;
select max(agg_test.fv) from agg_test;
select min(agg_test.iv) from agg_test;
select min(agg_test.sv) from agg_test;
select min(agg_test.dv) from agg_test;
select min(agg_test.fv) from agg_test;
select count(*) from agg_test;
select count(10) from agg_test;
select avg(agg_test.iv) from agg_test;
select avg(agg_test.fv) from agg_test;
select avg(2) from agg_test;
select max(iv) from agg_test;
select max(sv) from agg_test;
