drop table agg_test;
create table agg_test(id int, iv int, sv char, dv date, fv float);
insert into agg_test values(1, 1, "FNC", "2011-11-1", 3.0);
insert into agg_test values(2, 2, "TPA", "2012-11-1", 3.0);
insert into agg_test values(3, 3, "SKT", "2013-11-1", 3.0);
insert into agg_test values(4, 4, "SSW", "2014-11-1", 3.1);
select * from agg_test;
select max(iv), max(iv) from agg_test;
select max(iv), max(sv) from agg_test;
select max(iv), min(iv) from agg_test;
select max(iv), min(sv) from agg_test;
select max(iv), count(*) from agg_test;
select max(iv), count(10) from agg_test;
select max(iv), avg(iv) from agg_test;
select max(iv), avg(fv) from agg_test;
select max(iv), avg(2) from agg_test;
select count(*), max(iv) from agg_test;
select count(*), max(sv) from agg_test;
select count(*), min(iv) from agg_test;
select count(*), min(sv) from agg_test;
select count(*), count(*) from agg_test;
select count(*), count(10) from agg_test;
select count(*), avg(iv) from agg_test;
select count(*), avg(fv) from agg_test;
select count(*), avg(2) from agg_test;
select count(10), max(iv) from agg_test;
select count(10), max(sv) from agg_test;
select count(10), min(iv) from agg_test;
select count(10), min(sv) from agg_test;
select count(10), count(*) from agg_test;
select count(10), count(10) from agg_test;
select count(10), avg(iv) from agg_test;
select count(10), avg(fv) from agg_test;
select count(10), avg(2) from agg_test;
select avg(iv), max(iv) from agg_test;
select avg(iv), max(sv) from agg_test;
select avg(iv), min(iv) from agg_test;
select avg(iv), min(sv) from agg_test;
select avg(iv), count(*) from agg_test;
select avg(iv), count(10) from agg_test;
select avg(iv), avg(iv) from agg_test;
select avg(iv), avg(fv) from agg_test;
select avg(iv), avg(2) from agg_test;
select avg(2), max(iv) from agg_test;
select avg(2), max(sv) from agg_test;
select avg(2), min(iv) from agg_test;
select avg(2), min(sv) from agg_test;
select avg(2), count(*) from agg_test;
select avg(2), count(10) from agg_test;
select avg(2), avg(iv) from agg_test;
select avg(2), avg(fv) from agg_test;
select avg(2), avg(2) from agg_test;
