drop table t1;
drop table t2;
drop table t3;
create table t1(id int, age int, birthday date);
create table t2(id int, name char);
create table t3(id int, money float);
create index aid on t1(id);
create index bid on t2(id);
create index cid on t3(id);
insert into t1 values(1, 2, "1999-04-21"), (2, 3, "1998-04-21");
insert into t2 values(1, "a"), (2, "b");
insert into t3 values(1, 1.21);
insert into t3 values(2, 3.21);
select * from t1;
select * from t2;
select * from t3;
select * from t1, t2, t3;
