drop table agg_test;
create table agg_test(id int, iv int, sv char, dv date, fv float);
insert into agg_test values(1, 1, "FNC", "2011-11-1", 3.0);
insert into agg_test values(2, 1, "TPA", "2011-11-1", 3.0);
insert into agg_test values(3, 2, "TPA", "2013-11-1", 3.0);
insert into agg_test values(4, 2, "FNC", "2013-11-1", 3.1);
select * from agg_test;
select max(dv) from agg_test group by iv;
select max(dv) from agg_test group by sv;
select max(dv) from agg_test group by dv;
select min(dv) from agg_test group by iv;
select min(dv) from agg_test group by sv;
select min(dv) from agg_test group by dv;
select count(*) from agg_test group by iv;
select count(*) from agg_test group by sv;
select count(*) from agg_test group by dv;
select count(10) from agg_test group by iv;
select count(10) from agg_test group by sv;
select count(10) from agg_test group by dv;
select avg(fv) from agg_test group by iv;
select avg(fv) from agg_test group by sv;
select avg(fv) from agg_test group by dv;
select max(dv) from agg_test group by iv, sv;
select max(dv), min(fv) from agg_test group by iv, sv;
select max(agg_test.dv), min(fv) from agg_test group by iv, agg_test.sv;
