drop table agg_test;
create table agg_test(id int, iv int, sv char, dv date, fv float);
insert into agg_test values(1, 1, "FNC", "2011-11-1", 3.0);
insert into agg_test values(2, 1, "TPA", "2011-11-1", 3.0);
insert into agg_test values(3, 2, "TPA", "2013-11-1", 3.0);
insert into agg_test values(4, 2, "FNC", "2013-11-1", 3.1);
select * from agg_test;
select iv, max(dv) from agg_test group by iv;
select sv, max(dv) from agg_test group by sv;
select dv, max(dv) from agg_test group by dv;
select iv, min(dv) from agg_test group by iv;
select sv, min(dv) from agg_test group by sv;
select dv, min(dv) from agg_test group by dv;
select iv, count(*) from agg_test group by iv;
select sv, count(*) from agg_test group by sv;
select dv, count(*) from agg_test group by dv;
select iv, count(10) from agg_test group by iv;
select sv, count(10) from agg_test group by sv;
select dv, count(10) from agg_test group by dv;
select iv, avg(fv) from agg_test group by iv;
select sv, avg(fv) from agg_test group by sv;
select dv, avg(fv) from agg_test group by dv;
select iv, sv, max(dv) from agg_test group by iv, sv;
select iv, sv, max(dv), min(fv) from agg_test group by iv, sv;
select iv, agg_test.sv, max(agg_test.dv), min(fv) from agg_test group by iv, agg_test.sv;
