drop table t1;
drop table t2;
drop table t3;
create table t1(id int, age int, fv float);
create table t2(id int, age int, fv float);
create table t3(id int, age int, fv float);
insert into t1 values(1, 2, 1.0);
insert into t1 values(2, 3, 2.0);
insert into t1 values(3, 4, 3.0);
insert into t1 values(4, 5, 4.0);
insert into t2 values(1, 2, 1.0);
insert into t2 values(2, 3, 2.0);
insert into t2 values(3, 4, 3.0);
insert into t2 values(4, 5, 4.0);
insert into t3 values(1, 2, 1.0);
insert into t3 values(2, 3, 2.0);
insert into t3 values(3, 4, 3.0);
insert into t3 values(4, 5, 4.0);
select * from t1;
select * from t2;
select * from t3;
select * from t1 where id in (select id from t2 where id > 1);
select * from t1 where id in (select id from t2 where id < t1.id and id > 1);
select * from t1 where id in (select t2.id from t1 inner join t2 on t1.age = t2.id where t2.id > 2);
select * from t1 where id >= (select min(age) from t2);
select * from t1 where id > (select min(age) from t2);
select * from t1 where age >= (select count(*) from t2);
select * from t1 where age > (select count(*) from t2);
select * from t1 where id > (select avg(id) from t2);
select * from t1 where (select avg(id) from t2) > id;
SELECT * FROM t1 WHERE (SELECT AVG(t2.id) FROM t2) <> (SELECT AVG(t3.id) FROM t3);
SELECT * FROM t1 WHERE (SELECT max(t2.id) FROM t2) > (SELECT AVG(t3.id) FROM t3);
SELECT * FROM t1 WHERE (SELECT max(t2.id) FROM t2) < (SELECT AVG(t3.id) FROM t3);
select * from t1 where fv > (select avg(t2.fv) from t2 where t2.fv > t1.fv);
